[package]
name = "unrecoverable-errors-with-panic"
version = "0.1.0"
authors = ["Paul Razvan Berg <hello@paulrberg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
panic = "abort"
