[package]
name = "release-profiles"
version = "0.1.0"
authors = ["Paul Razvan Berg <hello@paulrberg.com>"]
edition = "2018"

# Override the default setting of 0.
[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
